version: '3.9'

services:

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=star_wars
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
  backend: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
     - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=:postgresql://admin:password@localhost:5432/star_wars
    depends_on:
      - postgres
    volumes:
      - ./:/src