version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=star_wars
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "star_wars"]
      interval: 30s
      timeout: 60s
      retries: 5
  
  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
     - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://admin:password@postgres:5432/star_wars
    volumes:
      - ./:/src